package com.IdeaBox.models.sugestoes;

public enum Status_Sugestao {
	EM_ANALISE_RH, APROVADO_PELO_RH, REPROVADO_PELO_RH, TOP_TREND ,EM_ANALISE_GERENCIA, APROVADO_GERENCIA, REPROVADO_GERENCIA,ARQUIVADO
}

